services:
  ipchecker.cacheapi:
    image: ipchecker.cacheapi
    build:
        context: .
        dockerfile: IPChecker.CacheApi/Dockerfile
  
  ipchecker.lookupapi:
    environment:
      - Endpoints__CacheApi=ipchecker.cacheapi
    image: ipchecker.lookupapi
    build:
      context: .
      dockerfile: IPChecker.LookupApi/Dockerfile  
  
  ipchecker.batchapi:
    environment:
      - Endpoints__CacheApi=ipchecker.cacheapi
    image: ipchecker.batchapi
    build:
        context: .
        dockerfile: IPChecker.BatchApi/Dockerfile    
